# Generated by Django 5.1.6 on 2025-03-06 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_backupmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupModel',
        ),
    ]
