# Generated by Django 5.1.6 on 2025-03-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_delete_backupmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='has_language_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='no_language_certificate',
            field=models.BooleanField(default=True),
        ),
    ]
