# Generated by Django 5.1.6 on 2025-03-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_contact_has_language_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='language_certificate',
            field=models.CharField(choices=[('Yes', 'Ha'), ('No', 'Yo‘q')], default='No', max_length=3),
        ),
    ]
