# Generated by Django 5.1.6 on 2025-03-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_contact_language_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='language_certificate',
            field=models.CharField(choices=[('IELTS', 'IELTS'), ('TOPIK', 'TOPIK'), ('No', 'ENDI OLAMAN')], default='No', max_length=11),
        ),
    ]
