# Generated by Django 5.1.6 on 2025-03-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_contact_language_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
