# Generated by Django 5.1.6 on 2025-03-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_indextitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField()),
            ],
        ),
    ]
