# Generated by Django 5.1.6 on 2025-03-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_succtext_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='succtext',
            name='title',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
