# Generated by Django 5.1.6 on 2025-03-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_succtext_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='succtext',
            name='title',
            field=models.TextField(blank=True, help_text='Bu yerga qisqa va aniq sarlavha yozing.', max_length=500, null=True),
        ),
    ]
