# Generated by Django 5.1.6 on 2025-03-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_botuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botuser',
            options={'verbose_name': 'Telegram Bot Foydalanuvchilari', 'verbose_name_plural': 'Bot Foydalanuvchilari'},
        ),
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'verbose_name': 'Telegram Bot Files', 'verbose_name_plural': 'Files'},
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
